import { ChevronLeft, ChevronRight, Menu } from 'lucide-react'
import { useFechaStore } from '../store/fechaStore.js'
import { Button } from './ui/button.js'
import { formatFechaTitle } from '../utils/formatDate.js'
import { useDiasStore } from '@/store/diasStore.js'
import Calendario from './Calendario.js'
import Sidebar from './Sidebar.js'
import { useEffect, useState } from 'react'
import { cn } from '@/lib/utils.js'

