"""rename activity default id

Revision ID: 1fae39e8e82c
Revises: 267f4987f895
Create Date: 2026-09-04 19:14:16.897561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fae39e8e82c'
down_revision: Union[str, Sequence[str], None] = '267f4987f895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_activity_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('fk_user_activity_default'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_user_default_activity', 'users', 'activities', ['default_activity_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.drop_column('users', 'activity_default_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_default_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_user_default_activity', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_activity_default'), 'users', 'activities', ['activity_default_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('users', 'default_activity_id')
    # ### end Alembic commands ###
