"""initial migration

Revision ID: 267f4987f895
Revises:
Create Date: 2026-08-14 19:20:37.918313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '267f4987f895'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column(
      'created_at', sa.Date(), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_default_id', sa.Uuid(), nullable=True),
    # sa.ForeignKeyConstraint(
    #   ['activity_default_id'],
    #   ['activities.id'],
    #   name='fk_user_activity_default',
    #   ondelete='RESTRICT',
    #   use_alter=True,
    # ),
    sa.PrimaryKeyConstraint('id'),
  )
  op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
  op.create_index(
    op.f('ix_users_google_id'), 'users', ['google_id'], unique=True
  )
  op.create_table(
    'categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_category_name_user'),
  )
  op.create_table(
    'days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'user_id'),
  )
  op.create_table(
    'refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
  )
  op.create_table(
    'activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(
      ['category_id'], ['categories.id'], ondelete='CASCADE'
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='uq_activity_name_user'),
  )
  op.create_table(
    'blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Time(), nullable=False),
    sa.Column('hour_end', sa.Time(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(
      ['activity_id'], ['activities.id'], ondelete='RESTRICT'
    ),
    sa.ForeignKeyConstraint(
      ['date', 'user_id'], ['days.date', 'days.user_id'], ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('id'),
  )
  op.create_table(
    'hidden_activities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(
      ['activity_id'], ['activities.id'], ondelete='CASCADE'
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'activity_id'),
  )
  # ### end Alembic commands ###

  op.create_foreign_key(
    'fk_user_activity_default',
    'users',
    'activities',
    ['activity_default_id'],
    ['id'],
    ondelete='RESTRICT',
  )


def downgrade() -> None:

  op.drop_constraint('fk_user_activity_default', 'users', type_='foreignkey')

  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('hidden_activities')
  op.drop_table('blocks')
  op.drop_table('activities')
  op.drop_table('refresh_tokens')
  op.drop_table('days')
  op.drop_table('categories')
  op.drop_index(op.f('ix_users_google_id'), table_name='users')
  op.drop_index(op.f('ix_users_email'), table_name='users')
  op.drop_table('users')
  # ### end Alembic commands ###
