DEFAULT_CATEGORY_NAME = 'Empty'
DEFAULT_CATEGORY_COLOR = '#A18072'
DEFAULT_ACTIVITY_NAME = 'Empty'
GRANULARITY_MINUTES = 30
GRANULARITY_HOURS = GRANULARITY_MINUTES / 60
GRACE_PERIOD_DAYS = 30
JWT_ALGORITHM = 'HS256'
